name: Feature Testing

on:
  pull_request:
    branches:
      - test
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest -vs
      - name: Trigger Jenkins Pipeline
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          curl -X POST ${{ secrets.JENKINS_WEBHOOK_URL }}